### ISSUE TITLE
Assignment01_draft (Not ready for grading)

### ISSUE THREAD

**Issue by LiMeng603** [SES-5215-F2020/mengyao_li-quant#1]
Hi Carole, The Assignment01_draft Markdown file is ready. I would be very grateful if we can solve these two technical problems:

1. When I try to knit my file, I constantly receive this error message: 

Error in pums_variables %>% distinct(year, survey, var_code, var_label, : No function "%>%" Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval

It seems that R cannot find the "%>%" function. However, I am pretty sure that I have loaded all packages that involve this function (such as "dplyr"), and the "%>%" works out fine when I write the markdown file. It just goes wrong when I try to knit it. 

2. When I try to access the area-level data, I receive an error message:

Error in open.connection(x, "rb"): Failed to connect to api.census.gov port 80: Timed out

It seems like a proxy problem. I have tried some methods posted on StackOverflow and turned my VPN on and off, yet the problem is still not solved.

**Comment by c-voulgaris** [comment]
For problem (1):

In line 8 of your Rmd file, change "eval=FALSE" to "message=FALSE".

"eval=FALSE" basically tells the knitter to skip that chunk when knitting the file, so tidyverse isn't getting loaded. "message=FALSE" will still run the code, but it just doesn't print the messages. You could also just delete "eval=FALSE" and not replace it with anything. It might clutter up your knitted html file with some messages about loading the packages, but that's not a big deal.

For problem (2):

I wasn't able to replicate this problem on my computer (your code runs on my computer just fine). My guess is that it's either related to a slow internet connection or maybe the Census website was just temporarily down when you tried it? At any rate, the household-level data seems to work just fine, so you've fulfilled the requirements for assignment 1 without doing anything with the area-level variables.

You could just delete everything after line 44 and and then submit this as is to receive close to full credit.

For full credit, you would also need to add commentary that explicitly describes your data. You would add a statement (around line 39 or so) like "This dataset includes 196,967 households." And you would also add some text around line 22 or so (before you list your variables) that says something like. "I am using household-level data" or "My unit of analysis is the household" and "My data includes all households in New York State."

I would also recommend replacing line 27 with 
```{r, results='hide'}

"results='hide'" will keep your knitted markdown file from including hundreds of lines of just:
Downloading: 8.6 kB     
Downloading: 8.6 kB     
Downloading: 8.6 kB     
Downloading: 8.6 kB     
Downloading: 18 kB     
Downloading: 18 kB     
Downloading: 18 kB     
Downloading: 18 kB     
Downloading: 18 kB     
Downloading: 18 kB     
Downloading: 18 kB     
Downloading: 18 kB     
Downloading: 27 kB     
Downloading: 27 kB     
Downloading: 27 kB     
Downloading: 27 kB     
Downloading: 27 kB     
Downloading: 27 kB

**Comment by LiMeng603** [comment]
Thank you very much for your help!!
I have solved the first issue with your suggestion. As for the second one, I found some answers on Stackoverflow that help. I have also added commentary to describe my data. Thanks again.
